update on shorting

diff --git a/ubuntu/bin/nas-utility b/ubuntu/bin/nas-utility
--- a/ubuntu/bin/nas-utility
+++ b/ubuntu/bin/nas-utility
@@ -19,7 +19,7 @@ parse_global_args() {
                 WHIPTAIL=true
                 shift
                 ;;
-            -*)
+            --*)
                 echo "Unknown global option: $1" >&2
                 exit 1
                 ;;
@@ -41,20 +41,95 @@ COMMAND=""
 ARGS=()
 
 
-
-
-install(){
-    
-
-
-}
-
-
-
-
 main() {
 
     parse_global_args "$@"
+
+
+    if [[ $WHIPTAIL == true ]]; then
+
+        # Check if Whiptail is installed
+        if ! command -v whiptail &> /dev/null; then
+            sudo apt update
+            sudo apt install whiptail -y
+        fi
+
+
+
+         while true; do
+            CHOICE=$(whiptail --title "Action Menu" --menu "Choose an option:" 20 60 10 \
+                "Install Menu" "" \
+                "Uninstall Menu" "" \
+                "Delete" "" \
+                "Exit" "" \
+                3>&1 1>&2 2>&3)
+
+            exitstatus=$?
+            if [ $exitstatus -ne 0 ] || [ -z "$CHOICE" ]; then
+                echo "No selection made. Exiting."
+                break
+            fi
+
+            case "$CHOICE" in
+                "Install Menu") install_menu ;;
+                "Uninstall Menu") uninstall_menu ;;
+                "Delete") delete_app ;;
+                "Exit") exit_program ;;
+                *) whiptail --title "Error" --msgbox "Invalid option selected!" 10 50 ;;
+            esac
+        done
+
+    else
+
+        case "${ARGS[0]}" in
+
+            "-i")
+                install_menu "${ARGS[@]}" 
+                ;;
+
+            "-u")
+                uninstall_menu "${ARGS[@]}" 
+                ;;
+
+            "-d")
+                delete_app 
+                ;;
+
+            *)
+                echo "Unknown command: $1"
+                exit 1
+                ;;
+
+        esac
+
+    fi
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
     # Define mapping between actions and functions
     declare -A ACTIONS=(
@@ -75,9 +150,9 @@ main() {
 
         while true; do
             CHOICE=$(whiptail --title "Action Menu" --menu "Choose an option:" 20 60 10 \
-                "install" "Install application" \
-                "uninstall" "Uninstall application" \
-                "delete" "Delete application" \
+                "install" "Install Application" \
+                "uninstall" "Uninstall Application" \
+                "delete" "Delete" \
                 "exit" "Exit program" \
                 3>&1 1>&2 2>&3)
 
@@ -87,13 +162,23 @@ main() {
                 break
             fi
 
+            case "$CHOICE" in
+                "Install Menu") install_menu ;;
+                "Uninstall Menu") uninstall_menu ;;
+                "Delete") delete_app ;;
+                "Exit") exit_program ;;
+                *) whiptail --title "Error" --msgbox "Invalid option selected!" 10 50 ;;
+            esac
+
             if [[ -n "${ACTIONS[$CHOICE]}" ]]; then
                 "${ACTIONS[$CHOICE]}" "${ARGS[@]}"
             else
                 whiptail --title "Error" --msgbox "Invalid option selected!" 10 50
             fi
         done
+
     else
+
         if [[ -n "${ACTIONS[$COMMAND]}" ]]; then
             "${ACTIONS[$COMMAND]}" "${ARGS[@]}"
         else
